// <auto-generated />
using System;
using DownloadStation.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DownloadStation.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309151902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("DownloadStation.Server.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Platform", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Software", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.SoftwarePlatform", b =>
                {
                    b.Property<string>("SoftwareId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("SoftwareId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SoftwarePlatforms");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.SoftwareScreenshot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareScreenshots");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.SoftwareVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Changelog")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashSHA256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("HashStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoftwareId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsVisible");

                    b.HasIndex("SoftwareId", "CreatedAt")
                        .IsDescending();

                    b.ToTable("SoftwareVersions");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Category", b =>
                {
                    b.HasOne("DownloadStation.Server.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Software", b =>
                {
                    b.HasOne("DownloadStation.Server.Models.Category", "Category")
                        .WithMany("Softwares")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.SoftwarePlatform", b =>
                {
                    b.HasOne("DownloadStation.Server.Models.Platform", "Platform")
                        .WithMany("SoftwarePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DownloadStation.Server.Models.Software", "Software")
                        .WithMany("SoftwarePlatforms")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.SoftwareScreenshot", b =>
                {
                    b.HasOne("DownloadStation.Server.Models.Software", "Software")
                        .WithMany("Screenshots")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.SoftwareVersion", b =>
                {
                    b.HasOne("DownloadStation.Server.Models.Software", "Software")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Softwares");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Platform", b =>
                {
                    b.Navigation("SoftwarePlatforms");
                });

            modelBuilder.Entity("DownloadStation.Server.Models.Software", b =>
                {
                    b.Navigation("Screenshots");

                    b.Navigation("SoftwarePlatforms");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
